### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Alexey1994** [ObaraEmmanuel/NES#1]
Hi. What license? Can i port your project to my OS? https://github.com/Alexey1994/BelOS

**Comment by ObaraEmmanuel** [comment]
You can use MIT licence. Let me add it.

**Comment by ObaraEmmanuel** [comment]
@Alexey1994 I have added the license to the master branch. Also, the master branch has no APU implemented but I have been working on it and I will merge when it is done. Stay tuned.

**Comment by Alexey1994** [comment]
Thanks, good work!

The most common error that I got was mapper 4.
Battletods works weird.
And here https://github.com/ObaraEmmanuel/NES/blob/master/src/ppu.c#L284 scanlines_per_frame instead of 261 is reset from the second line to zero. Compiled in tcc.
