### ISSUE TITLE
black screen problem in mmc1

### ISSUE THREAD

**Issue by jinjiacun123** [ObaraEmmanuel/NES#4]
i test a game rom with mmc1,but it show black.then, i use simple "hello world" that have two blank, is show normly.i find prg bank only use first bank and last bank,not use in other banks. This problem may be to related with it.

**Comment by ObaraEmmanuel** [comment]
Thanks for reporting I will look into it. If it is possible for you to provide the ROM file I would appreciate it.

**Comment by jinjiacun123** [comment]
i debug some code,find some situation.first, emulator not exec in rend bg,then i alter code like this:
 if((ppu->mask & SHOW_BG)
            || (ppu->mask & SHOW_BG_8)
old code is:
  if((ppu->mask & SHOW_BG)

but now find problem is cpu set $2001 first and second, after is no set $2001 register.i debug fceux thatn find first and second set $2001 is ok,it's value is 0x0 and 0x6, after than, is 0x6 ,0x1e and so on.
[hello_mmc1.zip](https://github.com/ObaraEmmanuel/NES/files/15480326/hello_mmc1.zip)

**Comment by ObaraEmmanuel** [comment]
@jinjiacun123 I have fixed the issue. Turns out your code relied on CPU dummy writes which I had not implemented. Once I implemented the dummy writes the MMC1 serial writes started working correctly. Let me know if you find other issues.

**Comment by jinjiacun123** [comment]
ok

**Comment by jinjiacun123** [comment]
can you give me some about cpu dummy media or textbook?I interest about NES emulator develop,but,know about it is very poor.

**Comment by ObaraEmmanuel** [comment]
@jinjiacun123 you can look at [this document](https://www.nesdev.org/6502_cpu.txt) for details on how the various types of instructions in 6502 are executed. It will show you what each instruction does per cycle including dummy writes and reads.

**Comment by ObaraEmmanuel** [comment]
@jinjiacun123, for details on what each 6502 instruction does one every cycle (including dummy writes and reads) you can checkout [this document](https://www.nesdev.org/6502_cpu.txt). For General details about the NES and emulation see the [NESDEV reference guide](https://www.nesdev.org/wiki/NES_reference_guide)

**Comment by jinjiacun123** [comment]
thank you.i will read about it.
